### PR TITLE
fix: make elapsedSeconds millis() rollover safe

### LINKED ISSUE #16: elapsedSeconds doesn't seem to be rollover-safe.
Since elapsedSeconds uses millis()/1000, I was curious about how it handles rollover so I took the example and reset the timer0_millis:

```
/*
  Simple demo of using all the timing helpers elapsedMillis makes available.

 Code from https://github.com/pfeerick/elapsedMillis/blob/master/examples/blinkingLeds/blinkingLeds.ino

  Modified to test the rollover of elapsedSeconds.
  Wokwi: https://wokwi.com/projects/402859003988453377

  See https://github.com/pfeerick/elapsedMillis/issues/16

  Either attach LEDs with series resistors to the indicated pins, or a
  six led / six bit 'Chartreuse' module plugged into pins 8 through GND.

  Wired up in order, the leds have a nice walking/counting effect.

  This example code is in the public domain.
*/

#include <elapsedMillis.h>  // https://github.com/pfeerick/elapsedMillis

//declare these global if you don't want them reset every time loop runs
elapsedMicros LED1micro;
elapsedMicros LED2micro;
elapsedMillis LED3millis;
elapsedMillis LED4millis;
elapsedSeconds LED5seconds;
elapsedSeconds LED6seconds;

const int LED1 = 8;
const int LED2 = 9;
const int LED3 = 10;
const int LED4 = 11;
const int LED5 = 12;
const int LED6 = 13;

// delay between blinks of the LED
unsigned long LED1_Interval = 62500;
unsigned long LED2_Interval = 125000;
unsigned long LED3_Interval = 250;
unsigned long LED4_Interval = 500;
unsigned long LED5_Interval = 1;
unsigned long LED6_Interval = 2;

extern volatile unsigned long timer0_millis;

void setup()
{
  // initialize the LED pins as outputs
  pinMode(LED1, OUTPUT);
  pinMode(LED2, OUTPUT);
  pinMode(LED3, OUTPUT);
  pinMode(LED4, OUTPUT);
  pinMode(LED5, OUTPUT);
  pinMode(LED6, OUTPUT);
  noInterrupts ();
  timer0_millis = -7200;
  interrupts ();

  LED1micro = LED2micro = LED3millis = LED4millis = LED5seconds = LED6seconds = 0;
}

void loop()
{
  if (LED1micro >= LED1_Interval)
  {
    digitalWrite(LED1, !(digitalRead(LED1))); // toggle the LED state
    LED1micro -= LED1_Interval;                           // reset the counter to 0 so the counting starts over...
  }

  if (LED2micro >= LED2_Interval)
  {
    digitalWrite(LED2, !(digitalRead(LED2))); // toggle the LED state
    LED2micro -= LED2_Interval;                            // reset the counter to 0 so the counting starts over...
  }

  if (LED3millis >= LED3_Interval)
  {
    digitalWrite(LED3, !(digitalRead(LED3))); // toggle the LED state
    LED3millis -= LED3_Interval;                           // reset the counter to 0 so the counting starts over...
  }

  if (LED4millis >= LED4_Interval)
  {
    digitalWrite(LED4, !(digitalRead(LED4))); // toggle the LED state
    LED4millis -= LED4_Interval;                           // reset the counter to 0 so the counting starts over...
  }

  if (LED5seconds >= LED5_Interval)
  {
    digitalWrite(LED5, !(digitalRead(LED5))); // toggle the LED state
    LED5seconds -= LED5_Interval;                          // reset the counter to 0 so the counting starts over...
  }

  if (LED6seconds >= LED6_Interval)
  {
    digitalWrite(LED6, !(digitalRead(LED6))); // toggle the LED state
    LED6seconds -= LED6_Interval;                         // reset the counter to 0 so the counting starts over...
  }
}
```

This code blinks the elapsedSeconds LEDs a couple times, and then they stick on.

Wokwi simulation:

https://wokwi.com/projects/402859003988453377

image

### PR DESCRIPTION
**Pull request by pfeerick**
Fixes #16 by using modular arithmetic - edit: which will never complete, so fall back to using ms internally

### CODE REVIEW

**Comment by drf5n** [comment]
I'm not sure that's the right modulus.

millis rolls over at 0xFFFFFFFF or 4294967295 the seconds rollover happens at  4294967295/1000 =  4294967 seconds with remainder 295ms.  Seconds (or any long) won't ever get big enough for `| 0xFFFFFFFF` to do anything.

**Comment by pfeerick** [comment]
Indeed... processing the wrong result. This version does appear to be working correctly now though

https://wokwi.com/projects/402972933691490305

**Comment by drf5n** [comment]
I wonder if the `*1000` constants should use `*1000UL`..

For lines like:

    elapsedSeconds operator + (int val) const           { elapsedSeconds r(*this); r.ms -= val * 1000; return r; }

...with a val like 33, 33*1000 could overflow the int on an Uno before it gets assigned into the unsigned long ms.

maybe a constant like:

    const unsigned long msPerSec = 1000;
    ...
    elapsedSeconds operator + (int val) const           { elapsedSeconds r(*this); r.ms -= val * msPerSec; return r; }
    ...

**Comment by pfeerick** [comment]
Yup, sounds good to me. It survived the test on wokwi and is working fine on a Atmega328 and ESP32-C6 (although I'm not sure of the direct timer reset there, so it is only a 'does the example run' test there). The changes in the assembly seem trivial... https://godbolt.org/z/dKPe61j7d ... plus anything that give the compiler hints on expected behaviour is good IMO ;)

**Pull request merged**
